In [1]:
import numpy as np
import pandas as pd

df=pd.read_csv("age_cul.csv")
print(df)

   age  weight  height  stanuthu
0    3      10     5.0     42.25
1   10      22     5.3     74.31
2   30      68     6.0    103.72
3   35      70     7.0    131.70
4   45      65     6.5    158.75
5   50      72     7.2    185.12
6   33      68     6.8    198.34
7   55      72     7.2    123.45
8   60      88     7.5    132.45


In [2]:
df

age  weight  height  stanuthu
0    3      10     5.0     42.25
1   10      22     5.3     74.31
2   30      68     6.0    103.72
3   35      70     7.0    131.70
4   45      65     6.5    158.75
5   50      72     7.2    185.12
6   33      68     6.8    198.34
7   55      72     7.2    123.45
8   60      88     7.5    132.45

In [3]:
df.head()

age  weight  height  stanuthu
0    3      10     5.0     42.25
1   10      22     5.3     74.31
2   30      68     6.0    103.72
3   35      70     7.0    131.70
4   45      65     6.5    158.75

In [4]:
df.tail()

age  weight  height  stanuthu
4   45      65     6.5    158.75
5   50      72     7.2    185.12
6   33      68     6.8    198.34
7   55      72     7.2    123.45
8   60      88     7.5    132.45

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       9 non-null      int64  
 1   weight    9 non-null      int64  
 2   height    9 non-null      float64
 3   stanuthu  9 non-null      float64
dtypes: float64(2), int64(2)
memory usage: 416.0 bytes


In [ ]:
check the missing values

In [6]:
#count the number of NaN values in each column
print(df.isnull().sum())

age         0
weight      0
height      0
stanuthu    0
dtype: int64


In [ ]:
#Split the dataset x values

In [7]:
X = df[['age','weight','height']][:].values.reshape(9, 3)
print(X)

[[ 3.  10.   5. ]
 [10.  22.   5.3]
 [30.  68.   6. ]
 [35.  70.   7. ]
 [45.  65.   6.5]
 [50.  72.   7.2]
 [33.  68.   6.8]
 [55.  72.   7.2]
 [60.  88.   7.5]]


In [8]:
y = df[['stanuthu']][:].values.reshape(9, 1)
print(y)

[[ 42.25]
 [ 74.31]
 [103.72]
 [131.7 ]
 [158.75]
 [185.12]
 [198.34]
 [123.45]
 [132.45]]


In [ ]:
#Implementing Random Forest Regressor using Sklearn

In [ ]:
Syntax:

from sklearn.ensemble import RandomForestRegressor


In [9]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(max_depth=5, random_state=0)

model.fit(X, y)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=5, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [ ]:
 #Predict New data

In [10]:
new_data = [3,24, 3.0]
print(model.predict([new_data]))

[62.1781]


In [ ]:
#Simplified Code

In [11]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor


df = pd.read_csv("age_cul.csv")
X = df[['age','weight','height' ]][:].values.reshape(9, 3)
y = df[['stanuthu']][:].values.reshape(9, 1)

model = RandomForestRegressor()
model.fit(X, y)
print(model.predict([[6,18, 3.7]]))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()


[64.2423]


In [ ]:
#Now its time to split train and test data

In [ ]:
#Working with the same dataset by splitting train and test data

In [12]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score


df = pd.read_csv("age_cul.csv")

X_train = df[['age','weight','height']][:6].values.reshape(6, 3)
y_train = df[['stanuthu']][:6].values.reshape(6, 1)

X_test = df[['age', 'weight', 'height' ]][6:].values.reshape(3, 3)
y_test = df[['stanuthu']][6:].values.reshape(3, 1)

model = RandomForestRegressor()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("R2 Score",r2_score(y_test, y_pred))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  app.launch_new_instance()


R2 Score -1.6087915816284952
