In [1]:
import numpy as np
import pandas as pd

df =pd.read_csv("age_cul.csv")
print(df)

   age  weight  height  stanuthu
0    3      10     5.0     42.25
1   10      22     5.3     74.31
2   30      68     6.0    103.72
3   35      70     7.0    131.70
4   45      65     6.5    158.75
5   50      72     7.2    185.12
6   33      68     6.8    198.34
7   55      72     7.2    123.45
8   60      88     7.5    132.45


In [2]:
df

age  weight  height  stanuthu
0    3      10     5.0     42.25
1   10      22     5.3     74.31
2   30      68     6.0    103.72
3   35      70     7.0    131.70
4   45      65     6.5    158.75
5   50      72     7.2    185.12
6   33      68     6.8    198.34
7   55      72     7.2    123.45
8   60      88     7.5    132.45

In [3]:
df.head()

age  weight  height  stanuthu
0    3      10     5.0     42.25
1   10      22     5.3     74.31
2   30      68     6.0    103.72
3   35      70     7.0    131.70
4   45      65     6.5    158.75

In [5]:
df.tail()

age  weight  height  stanuthu
4   45      65     6.5    158.75
5   50      72     7.2    185.12
6   33      68     6.8    198.34
7   55      72     7.2    123.45
8   60      88     7.5    132.45

In [6]:
df.describe()

age     weight   height    stanuthu
count   9.000000   9.000000  9.00000    9.000000
mean   35.666667  59.444444  6.50000  127.787778
std    19.442222  25.656925  0.88459   50.043680
min     3.000000  10.000000  5.00000   42.250000
25%    30.000000  65.000000  6.00000  103.720000
50%    35.000000  68.000000  6.80000  131.700000
75%    50.000000  72.000000  7.20000  158.750000
max    60.000000  88.000000  7.50000  198.340000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       9 non-null      int64  
 1   weight    9 non-null      int64  
 2   height    9 non-null      float64
 3   stanuthu  9 non-null      float64
dtypes: float64(2), int64(2)
memory usage: 416.0 bytes


In [ ]:
#Split the dataset x values

In [8]:
X = df[['age','weight','height']][:].values.reshape(9, 3)
print(X)

[[ 3.  10.   5. ]
 [10.  22.   5.3]
 [30.  68.   6. ]
 [35.  70.   7. ]
 [45.  65.   6.5]
 [50.  72.   7.2]
 [33.  68.   6.8]
 [55.  72.   7.2]
 [60.  88.   7.5]]


In [ ]:
#Split the dataset y values

In [9]:
y = df[['stanuthu']][:].values.reshape(9, 1)
print(y)

[[ 42.25]
 [ 74.31]
 [103.72]
 [131.7 ]
 [158.75]
 [185.12]
 [198.34]
 [123.45]
 [132.45]]


In [ ]:
#Implementing Support Vector Regression using Sklearn

In [ ]:
Syntax:

from sklearn import svm

In [10]:
from sklearn import svm
model = svm.SVR(kernel='rbf', C=1000)

model.fit(X, y)


/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1000, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
#Predict New data

In [11]:
new_data = [3,24, 3.0]
print(model.predict([new_data]))

[60.29614719]


In [14]:
new_data = [5,18, 3.5]
print(model.predict([new_data]))

[57.37153305]


In [ ]:
#Simplified Code

In [17]:
import pandas as pd
from sklearn.linear_model import Lasso

df = pd.read_csv("age_cul.csv")
X = df[['age','weight','height' ]][:].values.reshape(9, 3)
y = df[['stanuthu']][:].values.reshape(9, 1)

model = Lasso()
model.fit(X, y)
print(model.predict([[10,20, 5.5]]))

[77.22015447]


In [ ]:
#A Better Approach 

In [ ]:
#Now its time to split train and test data

In [ ]:
#Working with the same dataset by splitting train and test data

In [19]:
import numpy as np
import pandas as pd
from sklearn import svm

df = pd.read_csv("age_cul.csv")

X_train = df[['age', 'weight', 'height']][:6].values.reshape(6, 3)
y_train = df[['stanuthu']][:6].values.reshape(6, 1)

X_test = df[['age', 'weight', 'height']][6:].values.reshape(3, 3)
y_test = df[['stanuthu']][6:].values.reshape(3, 1)


model = svm.SVR(kernel='rbf', C=1000)
model.fit(X, y)

print("R2 Score",r2_score(y_test, y_pred))


R2 Score -4.04965821436211


/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
